#!/bin/sh

reset
clear

NAME=furiend_dc
RUNNING=$(docker container list --filter name=$NAME --quiet)
STOPPED=$(docker container list --all --filter name=$NAME --quiet)

if [ -n "$RUNNING" ]; then
    echo "docker container is already running: $NAME"
elif [ -n "$STOPPED" ]; then
    docker container start \
        --attach \
        --interactive \
        $NAME
else # not created
    docker container run \
        --tty \
        --interactive \
        --name $NAME \
        --workdir /furiend \
        --network furiend \
        --hostname dc \
        --ip 172.20.0.10 \
        --volume "$(pwd):/furiend/:rw" \
        --volume "$(pwd)/docker/.vimrc:/root/.vimrc:rw" \
        --volume "$(pwd)/docker/.profile:/root/.profile:rw" \
        --entrypoint /furiend/bin/lua \
        furiend \
        /furiend/src/dc/main.lua
fi
