#!/bin/sh

reset
clear

NAME=furiend_fe2
RUNNING=$(docker container list --filter name=$NAME --quiet)
STOPPED=$(docker container list --all --filter name=$NAME --quiet)

if [ -n "$RUNNING" ]; then
    echo "docker container is already running: $NAME"
elif [ -n "$STOPPED" ]; then
    docker container start \
        --attach \
        --interactive \
        $NAME
else # not created
    docker container run \
        --tty \
        --interactive \
        --name $NAME \
        --workdir /furiend \
        --network furiend \
        --hostname fe2 \
        --ip 172.20.0.5 \
        --env ENV=/root/.profile \
        --env IN_DOCKER=true \
        --volume "$(pwd):/furiend/:rw" \
        --volume "$(pwd)/docker/.vimrc:/root/.vimrc:rw" \
        --volume "$(pwd)/docker/.profile:/root/.profile:rw" \
        --entrypoint /furiend/bin/lua \
        --publish 127.0.0.1:19001:19001 \
        furiend \
        /furiend/src/fe2/main.lua
fi
