#!/bin/sh

reset
clear

NAME=furiend_redis
RUNNING=$(docker container list --filter name=$NAME --quiet)
STOPPED=$(docker container list --all --filter name=$NAME --quiet)

if [ -n "$RUNNING" ]; then
    echo "docker container is already running: $NAME"
elif [ -n "$STOPPED" ]; then
    docker container start \
        --attach \
        --interactive \
        $NAME
else # not created
    docker container run \
        --tty \
        --interactive \
        --name $NAME \
        --workdir /furiend \
        --network furiend \
        --hostname redis \
        --ip 172.20.0.3 \
        --volume "$(pwd):/furiend/:rw" \
        --volume "$(pwd)/docker/.vimrc:/root/.vimrc:rw" \
        --volume "$(pwd)/docker/.profile:/root/.profile:rw" \
        --entrypoint /furiend/bin/redis-server \
        --publish 127.0.0.1:30303:30303 \
        furiend \
        /furiend/docker/redis.conf
fi
